kind = "DojoModel"
class_hash = "0x13744470f93d6563afe6885e414af0255ad65506067bcc41752c0309c4b0178"
original_class_hash = "0x13744470f93d6563afe6885e414af0255ad65506067bcc41752c0309c4b0178"
abi = "manifests/dev/abis/base/models/dojo_starter_models_board_board.json"
name = "dojo_starter::models::board::board"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "rows"
type = "u8"
key = false

[[members]]
name = "max_movements"
type = "u8"
key = false
