kind = "DojoModel"
class_hash = "0x29b49a506213c4213b1a6c818b733a29cc95b053d84056d5524710543263e7"
original_class_hash = "0x29b49a506213c4213b1a6c818b733a29cc95b053d84056d5524710543263e7"
abi = "manifests/dev/abis/base/models/dojo_starter_models_leader_board_players.json"
name = "dojo_starter::models::leader_board::players"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "score"
type = "u32"
key = false
