kind = "DojoModel"
class_hash = "0x4c8b0840fc33053003dcfdc0530599403c664bf5ca3aafb57f36aa96743a8ee"
original_class_hash = "0x4c8b0840fc33053003dcfdc0530599403c664bf5ca3aafb57f36aa96743a8ee"
abi = "manifests/dev/abis/base/models/starktrip_models_tile_tile.json"
name = "starktrip::models::tile::tile"

[[members]]
name = "row_id"
type = "u32"
key = true

[[members]]
name = "col_id"
type = "u32"
key = true

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "value"
type = "felt252"
key = false
