kind = "DojoModel"
class_hash = "0x40970333f07645d666bd36e7cbffcbdad3de9c92bd0e8b59d8a97bd19f50e99"
original_class_hash = "0x40970333f07645d666bd36e7cbffcbdad3de9c92bd0e8b59d8a97bd19f50e99"
abi = "manifests/dev/abis/base/models/starktrip_models_leader_board_players_leader_board_players.json"
name = "starktrip::models::leader_board_players::leader_board_players"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "score"
type = "u32"
key = false
