kind = "DojoModel"
class_hash = "0x66b17153cc4a99ecc443e119ad2cd3e79dd783eb910adeda28db8d211d69843"
original_class_hash = "0x66b17153cc4a99ecc443e119ad2cd3e79dd783eb910adeda28db8d211d69843"
abi = "manifests/dev/abis/base/models/starktrip_models_spaceship_spaceship.json"
name = "starktrip::models::spaceship::spaceship"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "pos_x"
type = "u8"
key = false

[[members]]
name = "pos_y"
type = "u8"
key = false

[[members]]
name = "remaining_gas"
type = "u8"
key = false

[[members]]
name = "len_characters_inside"
type = "u8"
key = false
