kind = "DojoModel"
class_hash = "0x692c8573b227e84e34e440129ce136576773ecdd245f09e36bfc5b7301492f9"
original_class_hash = "0x692c8573b227e84e34e440129ce136576773ecdd245f09e36bfc5b7301492f9"
abi = "manifests/dev/abis/base/models/starktrip_models_board_board.json"
name = "starktrip::models::board::board"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "len_rows"
type = "u8"
key = false

[[members]]
name = "len_cols"
type = "u8"
key = false

[[members]]
name = "max_movements"
type = "u8"
key = false

[[members]]
name = "remaining_characters"
type = "u8"
key = false
