kind = "DojoModel"
class_hash = "0x544a4e9400ced9c1e589033064c3bc0fae6cf072619f5fd6fcb656d12a5e5da"
original_class_hash = "0x544a4e9400ced9c1e589033064c3bc0fae6cf072619f5fd6fcb656d12a5e5da"
abi = "manifests/dev/abis/base/models/starktrip_models_leader_board_players.json"
name = "starktrip::models::leader_board::players"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "score"
type = "u32"
key = false
