kind = "DojoModel"
class_hash = "0x77ccacdbfc50c17edd8d2bd6fe5adfb793be4d999e9e5155b2c78ee06367892"
original_class_hash = "0x77ccacdbfc50c17edd8d2bd6fe5adfb793be4d999e9e5155b2c78ee06367892"
abi = "manifests/dev/abis/base/models/starktrip_models_events_move.json"
name = "starktrip::models::events::move"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "pos_x"
type = "u8"
key = false

[[members]]
name = "pos_y"
type = "u8"
key = false

[[members]]
name = "remaining_gas"
type = "u8"
key = false
