kind = "DojoModel"
class_hash = "0x492bdc05dbcdb9fc9ab09befcb6e8238dd99e94237454824280f60229818723"
original_class_hash = "0x492bdc05dbcdb9fc9ab09befcb6e8238dd99e94237454824280f60229818723"
abi = "manifests/dev/abis/base/models/starktrip_models_leader_board_leader_board.json"
name = "starktrip::models::leader_board::leader_board"

[[members]]
name = "players"
type = "Players"
key = true

[[members]]
name = "score"
type = "u32"
key = false
