kind = "DojoModel"
class_hash = "0x1858c778a8e786dca7942ea429fdb02fa778319b6f96ec6d00a81402089c7d5"
original_class_hash = "0x1858c778a8e786dca7942ea429fdb02fa778319b6f96ec6d00a81402089c7d5"
abi = "manifests/dev/abis/base/models/starktrip_models_events_game_event.json"
name = "starktrip::models::events::game_event"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "round"
type = "u32"
key = false

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "state"
type = "bool"
key = false
