kind = "DojoModel"
class_hash = "0x76a2693e30dc32e616d15a532a893b059d52af257082582d7ff79a8e78141e5"
original_class_hash = "0x76a2693e30dc32e616d15a532a893b059d52af257082582d7ff79a8e78141e5"
abi = "manifests/dev/abis/base/models/starktrip_models_game_game.json"
name = "starktrip::models::game::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "spaceship_id"
type = "u32"
key = false

[[members]]
name = "board_id"
type = "u32"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "round"
type = "u32"
key = false

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "state"
type = "bool"
key = false
