kind = "DojoModel"
class_hash = "0x2d3cf70d18b17af235566a622a9ab6bae18fea4731516d6599054c4e21193ee"
original_class_hash = "0x2d3cf70d18b17af235566a622a9ab6bae18fea4731516d6599054c4e21193ee"
abi = "manifests/dev/abis/base/models/starktrip_models_events_game_over.json"
name = "starktrip::models::events::game_over"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_address"
type = "ContractAddress"
key = false
